public class QS_ProcessBuilderAbortProcess {
    
    /**
     * Explanation: This method will be invoked from the Process Builder when the Salesforce admin
     * does not want to execute any actions.
     * 
     * Once this idea is implemented https://success.salesforce.com/ideaView?id=08730000000DqGRAA0
     * this code will no longer be needed
     **/
    
    @InvocableMethod(label='Abort Process' description='Take no action and allow the process to be aborted.')
    public static void AbortProcess() {}
    
}